export const forecastData = {
  location: {
    name: "Melbourne",
    region: "Victoria",
    country: "Australia",
    lat: -37.82,
    lon: 144.97,
    tz_id: "Australia/Melbourne",
    localtime_epoch: 1650150922,
    localtime: "2022-04-17 9:15",
  },
  current: {
    last_updated_epoch: 1650146400,
    last_updated: "2022-04-17 08:00",
    temp_c: 18,
    temp_f: 64.4,
    is_day: 1,
    condition: {
      text: "Sunny",
      icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
      code: 1000,
    },
    wind_mph: 19.2,
    wind_kph: 31,
    wind_degree: 30,
    wind_dir: "NNE",
    pressure_mb: 1015,
    pressure_in: 29.97,
    precip_mm: 0,
    precip_in: 0,
    humidity: 56,
    cloud: 0,
    feelslike_c: 18,
    feelslike_f: 64.4,
    vis_km: 10,
    vis_miles: 6,
    uv: 5,
    gust_mph: 17.7,
    gust_kph: 28.4,
  },
  forecast: {
    forecastday: [
      {
        date: "2022-04-17",
        date_epoch: 1650153600,
        day: {
          maxtemp_c: 26.5,
          maxtemp_f: 79.7,
          mintemp_c: 16.4,
          mintemp_f: 61.5,
          avgtemp_c: 21,
          avgtemp_f: 69.8,
          maxwind_mph: 15.7,
          maxwind_kph: 25.2,
          totalprecip_mm: 0,
          totalprecip_in: 0,
          avgvis_km: 10,
          avgvis_miles: 6,
          avghumidity: 46,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 4,
        },
        astro: {
          sunrise: "06:48 AM",
          sunset: "05:51 PM",
          moonrise: "06:14 PM",
          moonset: "06:53 AM",
          moon_phase: "Waxing Gibbous",
          moon_illumination: "85",
        },
        hour: [
          {
            time_epoch: 1650117600,
            time: "2022-04-17 00:00",
            temp_c: 19,
            temp_f: 66.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 15,
            wind_dir: "NNE",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            humidity: 52,
            cloud: 10,
            feelslike_c: 19,
            feelslike_f: 66.2,
            windchill_c: 19,
            windchill_f: 66.2,
            heatindex_c: 19,
            heatindex_f: 66.2,
            dewpoint_c: 8.8,
            dewpoint_f: 47.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.7,
            gust_kph: 25.2,
            uv: 1,
          },
          {
            time_epoch: 1650121200,
            time: "2022-04-17 01:00",
            temp_c: 18.8,
            temp_f: 65.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 14,
            wind_dir: "NNE",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            humidity: 53,
            cloud: 10,
            feelslike_c: 18.8,
            feelslike_f: 65.8,
            windchill_c: 18.8,
            windchill_f: 65.8,
            heatindex_c: 18.8,
            heatindex_f: 65.8,
            dewpoint_c: 9.1,
            dewpoint_f: 48.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16.8,
            gust_kph: 27,
            uv: 1,
          },
          {
            time_epoch: 1650124800,
            time: "2022-04-17 02:00",
            temp_c: 18.3,
            temp_f: 64.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 10,
            wind_dir: "N",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 54,
            cloud: 8,
            feelslike_c: 18.3,
            feelslike_f: 64.9,
            windchill_c: 18.3,
            windchill_f: 64.9,
            heatindex_c: 18.3,
            heatindex_f: 64.9,
            dewpoint_c: 8.9,
            dewpoint_f: 48,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17.4,
            gust_kph: 28.1,
            uv: 1,
          },
          {
            time_epoch: 1650128400,
            time: "2022-04-17 03:00",
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 9,
            wind_dir: "N",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            humidity: 55,
            cloud: 5,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 8.8,
            dewpoint_f: 47.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17,
            gust_kph: 27.4,
            uv: 1,
          },
          {
            time_epoch: 1650132000,
            time: "2022-04-17 04:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 8,
            wind_dir: "N",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 56,
            cloud: 6,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: 8.6,
            dewpoint_f: 47.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16.1,
            gust_kph: 25.9,
            uv: 1,
          },
          {
            time_epoch: 1650135600,
            time: "2022-04-17 05:00",
            temp_c: 17.2,
            temp_f: 63,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 9,
            wind_dir: "N",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 57,
            cloud: 5,
            feelslike_c: 17.2,
            feelslike_f: 63,
            windchill_c: 17.2,
            windchill_f: 63,
            heatindex_c: 17.2,
            heatindex_f: 63,
            dewpoint_c: 8.6,
            dewpoint_f: 47.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 16.8,
            gust_kph: 27,
            uv: 1,
          },
          {
            time_epoch: 1650139200,
            time: "2022-04-17 06:00",
            temp_c: 16.7,
            temp_f: 62.1,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 10,
            wind_dir: "N",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 58,
            cloud: 4,
            feelslike_c: 16.7,
            feelslike_f: 62.1,
            windchill_c: 16.7,
            windchill_f: 62.1,
            heatindex_c: 16.7,
            heatindex_f: 62.1,
            dewpoint_c: 8.3,
            dewpoint_f: 46.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17.4,
            gust_kph: 28.1,
            uv: 1,
          },
          {
            time_epoch: 1650142800,
            time: "2022-04-17 07:00",
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 11.2,
            wind_kph: 18,
            wind_degree: 10,
            wind_dir: "N",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 58,
            cloud: 33,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            windchill_c: 16.4,
            windchill_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            dewpoint_c: 8.1,
            dewpoint_f: 46.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18.3,
            gust_kph: 29.5,
            uv: 5,
          },
          {
            time_epoch: 1650146400,
            time: "2022-04-17 08:00",
            temp_c: 17.3,
            temp_f: 63.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11.9,
            wind_kph: 19.1,
            wind_degree: 5,
            wind_dir: "N",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 54,
            cloud: 16,
            feelslike_c: 17.3,
            feelslike_f: 63.1,
            windchill_c: 17.3,
            windchill_f: 63.1,
            heatindex_c: 17.3,
            heatindex_f: 63.1,
            dewpoint_c: 7.9,
            dewpoint_f: 46.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17.7,
            gust_kph: 28.4,
            uv: 5,
          },
          {
            time_epoch: 1650150000,
            time: "2022-04-17 09:00",
            temp_c: 19.2,
            temp_f: 66.6,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 13.2,
            wind_kph: 21.2,
            wind_degree: 4,
            wind_dir: "N",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            humidity: 48,
            cloud: 11,
            feelslike_c: 19.2,
            feelslike_f: 66.6,
            windchill_c: 19.2,
            windchill_f: 66.6,
            heatindex_c: 19.2,
            heatindex_f: 66.6,
            dewpoint_c: 7.9,
            dewpoint_f: 46.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17.7,
            gust_kph: 28.4,
            uv: 5,
          },
          {
            time_epoch: 1650153600,
            time: "2022-04-17 10:00",
            temp_c: 21.1,
            temp_f: 70,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 14.8,
            wind_kph: 23.8,
            wind_degree: 1,
            wind_dir: "N",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 42,
            cloud: 0,
            feelslike_c: 21.1,
            feelslike_f: 70,
            windchill_c: 21.1,
            windchill_f: 70,
            heatindex_c: 24,
            heatindex_f: 75.2,
            dewpoint_c: 7.8,
            dewpoint_f: 46,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19,
            gust_kph: 30.6,
            uv: 6,
          },
          {
            time_epoch: 1650157200,
            time: "2022-04-17 11:00",
            temp_c: 22.1,
            temp_f: 71.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 15.7,
            wind_kph: 25.2,
            wind_degree: 0,
            wind_dir: "N",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0,
            precip_in: 0,
            humidity: 38,
            cloud: 2,
            feelslike_c: 23.9,
            feelslike_f: 75,
            windchill_c: 22.1,
            windchill_f: 71.8,
            heatindex_c: 23.9,
            heatindex_f: 75,
            dewpoint_c: 7.2,
            dewpoint_f: 45,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 23.5,
            gust_kph: 37.8,
            uv: 6,
          },
          {
            time_epoch: 1650160800,
            time: "2022-04-17 12:00",
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 15.7,
            wind_kph: 25.2,
            wind_degree: 0,
            wind_dir: "N",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0,
            precip_in: 0,
            humidity: 35,
            cloud: 4,
            feelslike_c: 24.4,
            feelslike_f: 75.9,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 7.5,
            dewpoint_f: 45.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 22.4,
            gust_kph: 36,
            uv: 6,
          },
          {
            time_epoch: 1650164400,
            time: "2022-04-17 13:00",
            temp_c: 23.8,
            temp_f: 74.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 15.4,
            wind_kph: 24.8,
            wind_degree: 352,
            wind_dir: "N",
            pressure_mb: 1012,
            pressure_in: 29.87,
            precip_mm: 0,
            precip_in: 0,
            humidity: 33,
            cloud: 3,
            feelslike_c: 24.2,
            feelslike_f: 75.6,
            windchill_c: 23.8,
            windchill_f: 74.8,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 6.5,
            dewpoint_f: 43.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 26.8,
            gust_kph: 43.2,
            uv: 6,
          },
          {
            time_epoch: 1650168000,
            time: "2022-04-17 14:00",
            temp_c: 24.9,
            temp_f: 76.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 15.2,
            wind_kph: 24.5,
            wind_degree: 350,
            wind_dir: "N",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0,
            precip_in: 0,
            humidity: 31,
            cloud: 5,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 24.9,
            windchill_f: 76.8,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 6.6,
            dewpoint_f: 43.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 26.2,
            gust_kph: 42.1,
            uv: 6,
          },
          {
            time_epoch: 1650171600,
            time: "2022-04-17 15:00",
            temp_c: 26.5,
            temp_f: 79.7,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 344,
            wind_dir: "NNW",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0,
            precip_in: 0,
            humidity: 30,
            cloud: 24,
            feelslike_c: 25.8,
            feelslike_f: 78.4,
            windchill_c: 26.5,
            windchill_f: 79.7,
            heatindex_c: 25.8,
            heatindex_f: 78.4,
            dewpoint_c: 7.7,
            dewpoint_f: 45.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 19.7,
            gust_kph: 31.7,
            uv: 7,
          },
          {
            time_epoch: 1650175200,
            time: "2022-04-17 16:00",
            temp_c: 26.1,
            temp_f: 79,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 11.6,
            wind_kph: 18.7,
            wind_degree: 350,
            wind_dir: "N",
            pressure_mb: 1010,
            pressure_in: 29.81,
            precip_mm: 0,
            precip_in: 0,
            humidity: 31,
            cloud: 33,
            feelslike_c: 25.5,
            feelslike_f: 77.9,
            windchill_c: 26.1,
            windchill_f: 79,
            heatindex_c: 25.5,
            heatindex_f: 77.9,
            dewpoint_c: 7.8,
            dewpoint_f: 46,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18.8,
            gust_kph: 30.2,
            uv: 7,
          },
          {
            time_epoch: 1650178800,
            time: "2022-04-17 17:00",
            temp_c: 25.3,
            temp_f: 77.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 346,
            wind_dir: "NNW",
            pressure_mb: 1010,
            pressure_in: 29.82,
            precip_mm: 0,
            precip_in: 0,
            humidity: 33,
            cloud: 46,
            feelslike_c: 25.1,
            feelslike_f: 77.2,
            windchill_c: 25.3,
            windchill_f: 77.5,
            heatindex_c: 25.1,
            heatindex_f: 77.2,
            dewpoint_c: 7.7,
            dewpoint_f: 45.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 18.1,
            gust_kph: 29.2,
            uv: 7,
          },
          {
            time_epoch: 1650182400,
            time: "2022-04-17 18:00",
            temp_c: 24.3,
            temp_f: 75.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 348,
            wind_dir: "NNW",
            pressure_mb: 1010,
            pressure_in: 29.83,
            precip_mm: 0,
            precip_in: 0,
            humidity: 34,
            cloud: 47,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 24.3,
            windchill_f: 75.7,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 7.4,
            dewpoint_f: 45.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 17.7,
            gust_kph: 28.4,
            uv: 1,
          },
          {
            time_epoch: 1650186000,
            time: "2022-04-17 19:00",
            temp_c: 23.7,
            temp_f: 74.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 354,
            wind_dir: "N",
            pressure_mb: 1011,
            pressure_in: 29.84,
            precip_mm: 0,
            precip_in: 0,
            humidity: 35,
            cloud: 49,
            feelslike_c: 24.4,
            feelslike_f: 75.9,
            windchill_c: 23.7,
            windchill_f: 74.7,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 7.4,
            dewpoint_f: 45.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.8,
            gust_kph: 23.8,
            uv: 1,
          },
          {
            time_epoch: 1650189600,
            time: "2022-04-17 20:00",
            temp_c: 23.2,
            temp_f: 73.8,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 6,
            wind_dir: "N",
            pressure_mb: 1011,
            pressure_in: 29.85,
            precip_mm: 0,
            precip_in: 0,
            humidity: 37,
            cloud: 66,
            feelslike_c: 24.2,
            feelslike_f: 75.6,
            windchill_c: 23.2,
            windchill_f: 73.8,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 7.6,
            dewpoint_f: 45.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 1,
          },
          {
            time_epoch: 1650193200,
            time: "2022-04-17 21:00",
            temp_c: 22.2,
            temp_f: 72,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 284,
            wind_dir: "WNW",
            pressure_mb: 1011,
            pressure_in: 29.86,
            precip_mm: 0,
            precip_in: 0,
            humidity: 43,
            cloud: 93,
            feelslike_c: 24.2,
            feelslike_f: 75.6,
            windchill_c: 22.2,
            windchill_f: 72,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 8.9,
            dewpoint_f: 48,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 1,
          },
          {
            time_epoch: 1650196800,
            time: "2022-04-17 22:00",
            temp_c: 19.6,
            temp_f: 67.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 219,
            wind_dir: "SW",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            humidity: 62,
            cloud: 59,
            feelslike_c: 19.6,
            feelslike_f: 67.3,
            windchill_c: 19.6,
            windchill_f: 67.3,
            heatindex_c: 19.6,
            heatindex_f: 67.3,
            dewpoint_c: 12.1,
            dewpoint_f: 53.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 15.2,
            gust_kph: 24.5,
            uv: 1,
          },
          {
            time_epoch: 1650200400,
            time: "2022-04-17 23:00",
            temp_c: 19,
            temp_f: 66.2,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 210,
            wind_dir: "SSW",
            pressure_mb: 1013,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 66,
            cloud: 88,
            feelslike_c: 19,
            feelslike_f: 66.2,
            windchill_c: 19,
            windchill_f: 66.2,
            heatindex_c: 19,
            heatindex_f: 66.2,
            dewpoint_c: 12.6,
            dewpoint_f: 54.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1,
          },
        ],
      },
      {
        date: "2022-04-18",
        date_epoch: 1650240000,
        day: {
          maxtemp_c: 16.2,
          maxtemp_f: 61.2,
          mintemp_c: 14.5,
          mintemp_f: 58.1,
          avgtemp_c: 15.7,
          avgtemp_f: 60.3,
          maxwind_mph: 10.7,
          maxwind_kph: 17.3,
          totalprecip_mm: 51.7,
          totalprecip_in: 2.04,
          avgvis_km: 7.2,
          avgvis_miles: 4,
          avghumidity: 88,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 91,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Heavy rain",
            icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
            code: 1195,
          },
          uv: 1,
        },
        astro: {
          sunrise: "06:49 AM",
          sunset: "05:50 PM",
          moonrise: "06:47 PM",
          moonset: "08:06 AM",
          moon_phase: "Waxing Gibbous",
          moon_illumination: "78",
        },
        hour: [
          {
            time_epoch: 1650204000,
            time: "2022-04-18 00:00",
            temp_c: 18.8,
            temp_f: 65.8,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 210,
            wind_dir: "SSW",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0,
            precip_in: 0,
            humidity: 68,
            cloud: 99,
            feelslike_c: 18.8,
            feelslike_f: 65.8,
            windchill_c: 18.8,
            windchill_f: 65.8,
            heatindex_c: 18.8,
            heatindex_f: 65.8,
            dewpoint_c: 12.8,
            dewpoint_f: 55,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 1,
          },
          {
            time_epoch: 1650207600,
            time: "2022-04-18 01:00",
            temp_c: 17.9,
            temp_f: 64.2,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 178,
            wind_dir: "S",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0.5,
            precip_in: 0.02,
            humidity: 76,
            cloud: 100,
            feelslike_c: 17.9,
            feelslike_f: 64.2,
            windchill_c: 17.9,
            windchill_f: 64.2,
            heatindex_c: 17.9,
            heatindex_f: 64.2,
            dewpoint_c: 13.5,
            dewpoint_f: 56.3,
            will_it_rain: 1,
            chance_of_rain: 91,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 1.6,
            gust_kph: 2.5,
            uv: 1,
          },
          {
            time_epoch: 1650211200,
            time: "2022-04-18 02:00",
            temp_c: 17.3,
            temp_f: 63.1,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 10,
            wind_dir: "N",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 80,
            cloud: 100,
            feelslike_c: 17.3,
            feelslike_f: 63.1,
            windchill_c: 17.3,
            windchill_f: 63.1,
            heatindex_c: 17.3,
            heatindex_f: 63.1,
            dewpoint_c: 13.9,
            dewpoint_f: 57,
            will_it_rain: 1,
            chance_of_rain: 90,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 1,
          },
          {
            time_epoch: 1650214800,
            time: "2022-04-18 03:00",
            temp_c: 16.7,
            temp_f: 62.1,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 357,
            wind_dir: "N",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0.5,
            precip_in: 0.02,
            humidity: 87,
            cloud: 95,
            feelslike_c: 16.7,
            feelslike_f: 62.1,
            windchill_c: 16.7,
            windchill_f: 62.1,
            heatindex_c: 16.7,
            heatindex_f: 62.1,
            dewpoint_c: 14.6,
            dewpoint_f: 58.3,
            will_it_rain: 1,
            chance_of_rain: 90,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 8.1,
            gust_kph: 13,
            uv: 1,
          },
          {
            time_epoch: 1650218400,
            time: "2022-04-18 04:00",
            temp_c: 16.3,
            temp_f: 61.3,
            is_day: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/302.png",
              code: 1189,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 28,
            wind_dir: "NNE",
            pressure_mb: 1012,
            pressure_in: 29.9,
            precip_mm: 4.9,
            precip_in: 0.19,
            humidity: 89,
            cloud: 100,
            feelslike_c: 16.3,
            feelslike_f: 61.3,
            windchill_c: 16.3,
            windchill_f: 61.3,
            heatindex_c: 16.3,
            heatindex_f: 61.3,
            dewpoint_c: 14.5,
            dewpoint_f: 58.1,
            will_it_rain: 1,
            chance_of_rain: 90,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7,
            vis_miles: 4,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 1,
          },
          {
            time_epoch: 1650222000,
            time: "2022-04-18 05:00",
            temp_c: 15.9,
            temp_f: 60.6,
            is_day: 0,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/293.png",
              code: 1180,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 22,
            wind_dir: "NNE",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 1.7,
            precip_in: 0.07,
            humidity: 90,
            cloud: 61,
            feelslike_c: 15.9,
            feelslike_f: 60.6,
            windchill_c: 15.9,
            windchill_f: 60.6,
            heatindex_c: 15.9,
            heatindex_f: 60.6,
            dewpoint_c: 14.3,
            dewpoint_f: 57.7,
            will_it_rain: 1,
            chance_of_rain: 79,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 15.4,
            gust_kph: 24.8,
            uv: 1,
          },
          {
            time_epoch: 1650225600,
            time: "2022-04-18 06:00",
            temp_c: 15.9,
            temp_f: 60.6,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 24,
            wind_dir: "NNE",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 1.2,
            precip_in: 0.05,
            humidity: 88,
            cloud: 96,
            feelslike_c: 15.9,
            feelslike_f: 60.6,
            windchill_c: 15.9,
            windchill_f: 60.6,
            heatindex_c: 15.9,
            heatindex_f: 60.6,
            dewpoint_c: 14,
            dewpoint_f: 57.2,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 15.7,
            gust_kph: 25.2,
            uv: 1,
          },
          {
            time_epoch: 1650229200,
            time: "2022-04-18 07:00",
            temp_c: 15.7,
            temp_f: 60.3,
            is_day: 1,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 12,
            wind_dir: "NNE",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 3.2,
            precip_in: 0.13,
            humidity: 89,
            cloud: 99,
            feelslike_c: 15.7,
            feelslike_f: 60.3,
            windchill_c: 15.7,
            windchill_f: 60.3,
            heatindex_c: 15.7,
            heatindex_f: 60.3,
            dewpoint_c: 13.9,
            dewpoint_f: 57,
            will_it_rain: 1,
            chance_of_rain: 75,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7,
            vis_miles: 4,
            gust_mph: 13.9,
            gust_kph: 22.3,
            uv: 4,
          },
          {
            time_epoch: 1650232800,
            time: "2022-04-18 08:00",
            temp_c: 15.9,
            temp_f: 60.6,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 8,
            wind_dir: "N",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 1.1,
            precip_in: 0.04,
            humidity: 90,
            cloud: 75,
            feelslike_c: 15.9,
            feelslike_f: 60.6,
            windchill_c: 15.9,
            windchill_f: 60.6,
            heatindex_c: 15.9,
            heatindex_f: 60.6,
            dewpoint_c: 14.2,
            dewpoint_f: 57.6,
            will_it_rain: 1,
            chance_of_rain: 88,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 4,
          },
          {
            time_epoch: 1650236400,
            time: "2022-04-18 09:00",
            temp_c: 16.1,
            temp_f: 61,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 7.4,
            wind_kph: 11.9,
            wind_degree: 343,
            wind_dir: "NNW",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 1.3,
            precip_in: 0.05,
            humidity: 91,
            cloud: 100,
            feelslike_c: 16.1,
            feelslike_f: 61,
            windchill_c: 16.1,
            windchill_f: 61,
            heatindex_c: 16.1,
            heatindex_f: 61,
            dewpoint_c: 14.7,
            dewpoint_f: 58.5,
            will_it_rain: 1,
            chance_of_rain: 88,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 10.5,
            gust_kph: 16.9,
            uv: 4,
          },
          {
            time_epoch: 1650240000,
            time: "2022-04-18 10:00",
            temp_c: 15.9,
            temp_f: 60.6,
            is_day: 1,
            condition: {
              text: "Heavy rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
              code: 1195,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 307,
            wind_dir: "NW",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 9.2,
            precip_in: 0.36,
            humidity: 93,
            cloud: 100,
            feelslike_c: 15.9,
            feelslike_f: 60.6,
            windchill_c: 15.9,
            windchill_f: 60.6,
            heatindex_c: 15.9,
            heatindex_f: 60.6,
            dewpoint_c: 14.7,
            dewpoint_f: 58.5,
            will_it_rain: 1,
            chance_of_rain: 88,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5,
            vis_miles: 3,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 4,
          },
          {
            time_epoch: 1650243600,
            time: "2022-04-18 11:00",
            temp_c: 16.2,
            temp_f: 61.2,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 6.7,
            wind_kph: 10.8,
            wind_degree: 246,
            wind_dir: "WSW",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0.9,
            precip_in: 0.04,
            humidity: 90,
            cloud: 100,
            feelslike_c: 16.2,
            feelslike_f: 61.2,
            windchill_c: 16.2,
            windchill_f: 61.2,
            heatindex_c: 16.2,
            heatindex_f: 61.2,
            dewpoint_c: 14.5,
            dewpoint_f: 58.1,
            will_it_rain: 1,
            chance_of_rain: 87,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 4,
          },
          {
            time_epoch: 1650247200,
            time: "2022-04-18 12:00",
            temp_c: 15,
            temp_f: 59,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 222,
            wind_dir: "SW",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 1.9,
            precip_in: 0.07,
            humidity: 92,
            cloud: 100,
            feelslike_c: 14.9,
            feelslike_f: 58.8,
            windchill_c: 14.9,
            windchill_f: 58.8,
            heatindex_c: 15,
            heatindex_f: 59,
            dewpoint_c: 13.7,
            dewpoint_f: 56.7,
            will_it_rain: 1,
            chance_of_rain: 87,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 6.7,
            gust_kph: 10.8,
            uv: 4,
          },
          {
            time_epoch: 1650250800,
            time: "2022-04-18 13:00",
            temp_c: 15,
            temp_f: 59,
            is_day: 1,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
              code: 1189,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 277,
            wind_dir: "W",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 5.2,
            precip_in: 0.2,
            humidity: 92,
            cloud: 100,
            feelslike_c: 15.5,
            feelslike_f: 59.9,
            windchill_c: 15.5,
            windchill_f: 59.9,
            heatindex_c: 15,
            heatindex_f: 59,
            dewpoint_c: 13.7,
            dewpoint_f: 56.7,
            will_it_rain: 1,
            chance_of_rain: 87,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7,
            vis_miles: 4,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 4,
          },
          {
            time_epoch: 1650254400,
            time: "2022-04-18 14:00",
            temp_c: 15,
            temp_f: 59,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 12,
            wind_dir: "NNE",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 1.7,
            precip_in: 0.07,
            humidity: 92,
            cloud: 100,
            feelslike_c: 15,
            feelslike_f: 59,
            windchill_c: 15,
            windchill_f: 59,
            heatindex_c: 15,
            heatindex_f: 59,
            dewpoint_c: 13.7,
            dewpoint_f: 56.7,
            will_it_rain: 1,
            chance_of_rain: 86,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 1.3,
            gust_kph: 2.2,
            uv: 4,
          },
          {
            time_epoch: 1650258000,
            time: "2022-04-18 15:00",
            temp_c: 15.2,
            temp_f: 59.4,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 26,
            wind_dir: "NNE",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 1.7,
            precip_in: 0.07,
            humidity: 92,
            cloud: 100,
            feelslike_c: 15.2,
            feelslike_f: 59.4,
            windchill_c: 15.2,
            windchill_f: 59.4,
            heatindex_c: 15.2,
            heatindex_f: 59.4,
            dewpoint_c: 13.9,
            dewpoint_f: 57,
            will_it_rain: 1,
            chance_of_rain: 86,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 4,
          },
          {
            time_epoch: 1650261600,
            time: "2022-04-18 16:00",
            temp_c: 15.5,
            temp_f: 59.9,
            is_day: 1,
            condition: {
              text: "Heavy rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/308.png",
              code: 1195,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 16,
            wind_dir: "NNE",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 8.9,
            precip_in: 0.35,
            humidity: 89,
            cloud: 97,
            feelslike_c: 15.5,
            feelslike_f: 59.9,
            windchill_c: 15.5,
            windchill_f: 59.9,
            heatindex_c: 15.5,
            heatindex_f: 59.9,
            dewpoint_c: 13.7,
            dewpoint_f: 56.7,
            will_it_rain: 1,
            chance_of_rain: 86,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5,
            vis_miles: 3,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 4,
          },
          {
            time_epoch: 1650265200,
            time: "2022-04-18 17:00",
            temp_c: 15,
            temp_f: 59,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 47,
            wind_dir: "NE",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 1.3,
            precip_in: 0.05,
            humidity: 92,
            cloud: 86,
            feelslike_c: 14.7,
            feelslike_f: 58.5,
            windchill_c: 14.7,
            windchill_f: 58.5,
            heatindex_c: 15,
            heatindex_f: 59,
            dewpoint_c: 13.7,
            dewpoint_f: 56.7,
            will_it_rain: 1,
            chance_of_rain: 85,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 8.3,
            gust_kph: 13.3,
            uv: 4,
          },
          {
            time_epoch: 1650268800,
            time: "2022-04-18 18:00",
            temp_c: 14.9,
            temp_f: 58.8,
            is_day: 0,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/293.png",
              code: 1180,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 35,
            wind_dir: "NE",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 1.1,
            precip_in: 0.04,
            humidity: 92,
            cloud: 72,
            feelslike_c: 14.5,
            feelslike_f: 58.1,
            windchill_c: 14.5,
            windchill_f: 58.1,
            heatindex_c: 14.9,
            heatindex_f: 58.8,
            dewpoint_c: 13.7,
            dewpoint_f: 56.7,
            will_it_rain: 1,
            chance_of_rain: 85,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 9.4,
            gust_kph: 15.1,
            uv: 1,
          },
          {
            time_epoch: 1650272400,
            time: "2022-04-18 19:00",
            temp_c: 14.7,
            temp_f: 58.5,
            is_day: 0,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/293.png",
              code: 1180,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 50,
            wind_dir: "NE",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 2.4,
            precip_in: 0.09,
            humidity: 92,
            cloud: 62,
            feelslike_c: 14.5,
            feelslike_f: 58.1,
            windchill_c: 14.5,
            windchill_f: 58.1,
            heatindex_c: 14.7,
            heatindex_f: 58.5,
            dewpoint_c: 13.3,
            dewpoint_f: 55.9,
            will_it_rain: 0,
            chance_of_rain: 52,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 7.8,
            gust_kph: 12.6,
            uv: 1,
          },
          {
            time_epoch: 1650276000,
            time: "2022-04-18 20:00",
            temp_c: 14.8,
            temp_f: 58.6,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 37,
            wind_dir: "NE",
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 0.5,
            precip_in: 0.02,
            humidity: 90,
            cloud: 100,
            feelslike_c: 14.9,
            feelslike_f: 58.8,
            windchill_c: 14.9,
            windchill_f: 58.8,
            heatindex_c: 14.8,
            heatindex_f: 58.6,
            dewpoint_c: 13.2,
            dewpoint_f: 55.8,
            will_it_rain: 0,
            chance_of_rain: 61,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 1,
          },
          {
            time_epoch: 1650279600,
            time: "2022-04-18 21:00",
            temp_c: 14.8,
            temp_f: 58.6,
            is_day: 0,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/263.png",
              code: 1150,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 164,
            wind_dir: "SSE",
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 0.5,
            precip_in: 0.02,
            humidity: 89,
            cloud: 58,
            feelslike_c: 14.8,
            feelslike_f: 58.6,
            windchill_c: 14.8,
            windchill_f: 58.6,
            heatindex_c: 14.8,
            heatindex_f: 58.6,
            dewpoint_c: 12.9,
            dewpoint_f: 55.2,
            will_it_rain: 1,
            chance_of_rain: 84,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5,
            vis_miles: 3,
            gust_mph: 1.3,
            gust_kph: 2.2,
            uv: 1,
          },
          {
            time_epoch: 1650283200,
            time: "2022-04-18 22:00",
            temp_c: 14.7,
            temp_f: 58.5,
            is_day: 0,
            condition: {
              text: "Patchy light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/293.png",
              code: 1180,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 89,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 1.7,
            precip_in: 0.07,
            humidity: 89,
            cloud: 55,
            feelslike_c: 14.8,
            feelslike_f: 58.6,
            windchill_c: 14.8,
            windchill_f: 58.6,
            heatindex_c: 14.7,
            heatindex_f: 58.5,
            dewpoint_c: 13,
            dewpoint_f: 55.4,
            will_it_rain: 0,
            chance_of_rain: 52,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 6.3,
            gust_kph: 10.1,
            uv: 1,
          },
          {
            time_epoch: 1650286800,
            time: "2022-04-18 23:00",
            temp_c: 14.5,
            temp_f: 58.1,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 88,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 90,
            cloud: 80,
            feelslike_c: 14.7,
            feelslike_f: 58.5,
            windchill_c: 14.7,
            windchill_f: 58.5,
            heatindex_c: 14.5,
            heatindex_f: 58.1,
            dewpoint_c: 12.8,
            dewpoint_f: 55,
            will_it_rain: 0,
            chance_of_rain: 60,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 1,
          },
        ],
      },
      {
        date: "2022-04-19",
        date_epoch: 1650326400,
        day: {
          maxtemp_c: 14.9,
          maxtemp_f: 58.8,
          mintemp_c: 14.1,
          mintemp_f: 57.4,
          avgtemp_c: 14.4,
          avgtemp_f: 58,
          maxwind_mph: 9.4,
          maxwind_kph: 15.1,
          totalprecip_mm: 16,
          totalprecip_in: 0.63,
          avgvis_km: 6.3,
          avgvis_miles: 3,
          avghumidity: 89,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 82,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Moderate rain",
            icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
            code: 1189,
          },
          uv: 1,
        },
        astro: {
          sunrise: "06:50 AM",
          sunset: "05:48 PM",
          moonrise: "07:26 PM",
          moonset: "09:21 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: "70",
        },
        hour: [
          {
            time_epoch: 1650290400,
            time: "2022-04-19 00:00",
            temp_c: 14.6,
            temp_f: 58.3,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 94,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 90,
            cloud: 69,
            feelslike_c: 14.9,
            feelslike_f: 58.8,
            windchill_c: 14.9,
            windchill_f: 58.8,
            heatindex_c: 14.6,
            heatindex_f: 58.3,
            dewpoint_c: 13,
            dewpoint_f: 55.4,
            will_it_rain: 0,
            chance_of_rain: 59,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 1,
          },
          {
            time_epoch: 1650294000,
            time: "2022-04-19 01:00",
            temp_c: 14.4,
            temp_f: 57.9,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 102,
            wind_dir: "ESE",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 1,
            precip_in: 0.04,
            humidity: 92,
            cloud: 85,
            feelslike_c: 14.7,
            feelslike_f: 58.5,
            windchill_c: 14.7,
            windchill_f: 58.5,
            heatindex_c: 14.4,
            heatindex_f: 57.9,
            dewpoint_c: 13.1,
            dewpoint_f: 55.6,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 1,
          },
          {
            time_epoch: 1650297600,
            time: "2022-04-19 02:00",
            temp_c: 14.3,
            temp_f: 57.7,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 100,
            wind_dir: "E",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 92,
            cloud: 82,
            feelslike_c: 14.7,
            feelslike_f: 58.5,
            windchill_c: 14.7,
            windchill_f: 58.5,
            heatindex_c: 14.3,
            heatindex_f: 57.7,
            dewpoint_c: 13.1,
            dewpoint_f: 55.6,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 1,
          },
          {
            time_epoch: 1650301200,
            time: "2022-04-19 03:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 108,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0.6,
            precip_in: 0.02,
            humidity: 94,
            cloud: 93,
            feelslike_c: 14.3,
            feelslike_f: 57.7,
            windchill_c: 14.3,
            windchill_f: 57.7,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 13.2,
            dewpoint_f: 55.8,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 5.6,
            gust_kph: 9,
            uv: 1,
          },
          {
            time_epoch: 1650304800,
            time: "2022-04-19 04:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Moderate rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/302.png",
              code: 1189,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 108,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 3.4,
            precip_in: 0.13,
            humidity: 94,
            cloud: 93,
            feelslike_c: 14.6,
            feelslike_f: 58.3,
            windchill_c: 14.6,
            windchill_f: 58.3,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 13.2,
            dewpoint_f: 55.8,
            will_it_rain: 1,
            chance_of_rain: 81,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7,
            vis_miles: 4,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 1,
          },
          {
            time_epoch: 1650308400,
            time: "2022-04-19 05:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 90,
            wind_dir: "E",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0.5,
            precip_in: 0.02,
            humidity: 94,
            cloud: 85,
            feelslike_c: 13.8,
            feelslike_f: 56.8,
            windchill_c: 13.8,
            windchill_f: 56.8,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 13.2,
            dewpoint_f: 55.8,
            will_it_rain: 0,
            chance_of_rain: 63,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 1,
          },
          {
            time_epoch: 1650312000,
            time: "2022-04-19 06:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 113,
            wind_dir: "ESE",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 93,
            cloud: 81,
            feelslike_c: 14.8,
            feelslike_f: 58.6,
            windchill_c: 14.8,
            windchill_f: 58.6,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 13.1,
            dewpoint_f: 55.6,
            will_it_rain: 1,
            chance_of_rain: 81,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 1,
          },
          {
            time_epoch: 1650315600,
            time: "2022-04-19 07:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 140,
            wind_dir: "SE",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 1.3,
            precip_in: 0.05,
            humidity: 93,
            cloud: 88,
            feelslike_c: 14.2,
            feelslike_f: 57.6,
            windchill_c: 14.2,
            windchill_f: 57.6,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 13.1,
            dewpoint_f: 55.6,
            will_it_rain: 1,
            chance_of_rain: 80,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 2,
            gust_kph: 3.2,
            uv: 3,
          },
          {
            time_epoch: 1650319200,
            time: "2022-04-19 08:00",
            temp_c: 14.5,
            temp_f: 58.1,
            is_day: 1,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/266.png",
              code: 1153,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 163,
            wind_dir: "SSE",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 93,
            cloud: 87,
            feelslike_c: 14.8,
            feelslike_f: 58.6,
            windchill_c: 14.8,
            windchill_f: 58.6,
            heatindex_c: 14.5,
            heatindex_f: 58.1,
            dewpoint_c: 13.3,
            dewpoint_f: 55.9,
            will_it_rain: 1,
            chance_of_rain: 80,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 3,
          },
          {
            time_epoch: 1650322800,
            time: "2022-04-19 09:00",
            temp_c: 14.7,
            temp_f: 58.5,
            is_day: 1,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/266.png",
              code: 1153,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 167,
            wind_dir: "SSE",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 91,
            cloud: 86,
            feelslike_c: 14.8,
            feelslike_f: 58.6,
            windchill_c: 14.8,
            windchill_f: 58.6,
            heatindex_c: 14.7,
            heatindex_f: 58.5,
            dewpoint_c: 13.3,
            dewpoint_f: 55.9,
            will_it_rain: 1,
            chance_of_rain: 80,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 5.1,
            gust_kph: 8.3,
            uv: 3,
          },
          {
            time_epoch: 1650326400,
            time: "2022-04-19 10:00",
            temp_c: 14.7,
            temp_f: 58.5,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 164,
            wind_dir: "SSE",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 2,
            precip_in: 0.08,
            humidity: 91,
            cloud: 100,
            feelslike_c: 15,
            feelslike_f: 59,
            windchill_c: 15,
            windchill_f: 59,
            heatindex_c: 14.7,
            heatindex_f: 58.5,
            dewpoint_c: 13.3,
            dewpoint_f: 55.9,
            will_it_rain: 1,
            chance_of_rain: 79,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 3,
          },
          {
            time_epoch: 1650330000,
            time: "2022-04-19 11:00",
            temp_c: 14.9,
            temp_f: 58.8,
            is_day: 1,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/266.png",
              code: 1153,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 157,
            wind_dir: "SSE",
            pressure_mb: 1014,
            pressure_in: 29.96,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 90,
            cloud: 99,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 14.9,
            heatindex_f: 58.8,
            dewpoint_c: 13.3,
            dewpoint_f: 55.9,
            will_it_rain: 1,
            chance_of_rain: 79,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 4.3,
            gust_kph: 6.8,
            uv: 3,
          },
          {
            time_epoch: 1650333600,
            time: "2022-04-19 12:00",
            temp_c: 14.8,
            temp_f: 58.6,
            is_day: 1,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/266.png",
              code: 1153,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 150,
            wind_dir: "SSE",
            pressure_mb: 1014,
            pressure_in: 29.94,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 90,
            cloud: 87,
            feelslike_c: 15.4,
            feelslike_f: 59.7,
            windchill_c: 15.4,
            windchill_f: 59.7,
            heatindex_c: 14.8,
            heatindex_f: 58.6,
            dewpoint_c: 13.2,
            dewpoint_f: 55.8,
            will_it_rain: 0,
            chance_of_rain: 68,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 3,
          },
          {
            time_epoch: 1650337200,
            time: "2022-04-19 13:00",
            temp_c: 14.7,
            temp_f: 58.5,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 170,
            wind_dir: "S",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0.9,
            precip_in: 0.04,
            humidity: 91,
            cloud: 100,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 14.7,
            heatindex_f: 58.5,
            dewpoint_c: 13.3,
            dewpoint_f: 55.9,
            will_it_rain: 1,
            chance_of_rain: 78,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 3,
          },
          {
            time_epoch: 1650340800,
            time: "2022-04-19 14:00",
            temp_c: 14.8,
            temp_f: 58.6,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 179,
            wind_dir: "S",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 92,
            cloud: 100,
            feelslike_c: 14.8,
            feelslike_f: 58.6,
            windchill_c: 14.8,
            windchill_f: 58.6,
            heatindex_c: 14.8,
            heatindex_f: 58.6,
            dewpoint_c: 13.4,
            dewpoint_f: 56.1,
            will_it_rain: 0,
            chance_of_rain: 58,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.8,
            gust_kph: 9.4,
            uv: 3,
          },
          {
            time_epoch: 1650344400,
            time: "2022-04-19 15:00",
            temp_c: 14.8,
            temp_f: 58.6,
            is_day: 1,
            condition: {
              text: "Light rain shower",
              icon: "//cdn.weatherapi.com/weather/64x64/day/353.png",
              code: 1240,
            },
            wind_mph: 6.5,
            wind_kph: 10.4,
            wind_degree: 175,
            wind_dir: "S",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 91,
            cloud: 100,
            feelslike_c: 14.3,
            feelslike_f: 57.7,
            windchill_c: 14.3,
            windchill_f: 57.7,
            heatindex_c: 14.8,
            heatindex_f: 58.6,
            dewpoint_c: 13.4,
            dewpoint_f: 56.1,
            will_it_rain: 0,
            chance_of_rain: 56,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 3,
          },
          {
            time_epoch: 1650348000,
            time: "2022-04-19 16:00",
            temp_c: 14.6,
            temp_f: 58.3,
            is_day: 1,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/day/296.png",
              code: 1183,
            },
            wind_mph: 8.3,
            wind_kph: 13.3,
            wind_degree: 183,
            wind_dir: "S",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 2.4,
            precip_in: 0.09,
            humidity: 90,
            cloud: 100,
            feelslike_c: 13.8,
            feelslike_f: 56.8,
            windchill_c: 13.8,
            windchill_f: 56.8,
            heatindex_c: 14.6,
            heatindex_f: 58.3,
            dewpoint_c: 12.9,
            dewpoint_f: 55.2,
            will_it_rain: 1,
            chance_of_rain: 77,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 11.6,
            gust_kph: 18.7,
            uv: 3,
          },
          {
            time_epoch: 1650351600,
            time: "2022-04-19 17:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 182,
            wind_dir: "S",
            pressure_mb: 1014,
            pressure_in: 29.93,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 87,
            cloud: 100,
            feelslike_c: 13.1,
            feelslike_f: 55.6,
            windchill_c: 13.1,
            windchill_f: 55.6,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 12.1,
            dewpoint_f: 53.8,
            will_it_rain: 0,
            chance_of_rain: 57,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 3,
          },
          {
            time_epoch: 1650355200,
            time: "2022-04-19 18:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 186,
            wind_dir: "S",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 85,
            cloud: 100,
            feelslike_c: 13.2,
            feelslike_f: 55.8,
            windchill_c: 13.2,
            windchill_f: 55.8,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 11.7,
            dewpoint_f: 53.1,
            will_it_rain: 0,
            chance_of_rain: 65,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.2,
            gust_kph: 21.2,
            uv: 1,
          },
          {
            time_epoch: 1650358800,
            time: "2022-04-19 19:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 186,
            wind_dir: "S",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 84,
            cloud: 100,
            feelslike_c: 13.3,
            feelslike_f: 55.9,
            windchill_c: 13.3,
            windchill_f: 55.9,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 11.4,
            dewpoint_f: 52.5,
            will_it_rain: 0,
            chance_of_rain: 65,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 12.1,
            gust_kph: 19.4,
            uv: 1,
          },
          {
            time_epoch: 1650362400,
            time: "2022-04-19 20:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 8.1,
            wind_kph: 13,
            wind_degree: 182,
            wind_dir: "S",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 83,
            cloud: 100,
            feelslike_c: 13.3,
            feelslike_f: 55.9,
            windchill_c: 13.3,
            windchill_f: 55.9,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 11.4,
            dewpoint_f: 52.5,
            will_it_rain: 1,
            chance_of_rain: 76,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 12.1,
            gust_kph: 19.4,
            uv: 1,
          },
          {
            time_epoch: 1650366000,
            time: "2022-04-19 21:00",
            temp_c: 14.1,
            temp_f: 57.4,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 190,
            wind_dir: "S",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0.1,
            precip_in: 0,
            humidity: 82,
            cloud: 100,
            feelslike_c: 13.1,
            feelslike_f: 55.6,
            windchill_c: 13.1,
            windchill_f: 55.6,
            heatindex_c: 14.1,
            heatindex_f: 57.4,
            dewpoint_c: 11.1,
            dewpoint_f: 52,
            will_it_rain: 1,
            chance_of_rain: 80,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.4,
            gust_kph: 21.6,
            uv: 1,
          },
          {
            time_epoch: 1650369600,
            time: "2022-04-19 22:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 0,
            condition: {
              text: "Light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/266.png",
              code: 1153,
            },
            wind_mph: 6.9,
            wind_kph: 11.2,
            wind_degree: 185,
            wind_dir: "S",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0.4,
            precip_in: 0.02,
            humidity: 81,
            cloud: 100,
            feelslike_c: 13.5,
            feelslike_f: 56.3,
            windchill_c: 13.5,
            windchill_f: 56.3,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            dewpoint_c: 11,
            dewpoint_f: 51.8,
            will_it_rain: 1,
            chance_of_rain: 76,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 10.7,
            gust_kph: 17.3,
            uv: 1,
          },
          {
            time_epoch: 1650373200,
            time: "2022-04-19 23:00",
            temp_c: 14.1,
            temp_f: 57.4,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 8.7,
            wind_kph: 14,
            wind_degree: 203,
            wind_dir: "SSW",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 80,
            cloud: 100,
            feelslike_c: 13.1,
            feelslike_f: 55.6,
            windchill_c: 13.1,
            windchill_f: 55.6,
            heatindex_c: 14.1,
            heatindex_f: 57.4,
            dewpoint_c: 10.7,
            dewpoint_f: 51.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 13.6,
            gust_kph: 22,
            uv: 1,
          },
        ],
      },
    ],
  },
};
